// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxVimPpg8k3DkuQLvjCZwiHcmQ7aB15A',
    appId: '1:874274763327:web:008f94f151912e9625be8a',
    messagingSenderId: '874274763327',
    projectId: 'senior-app-2adee',
    authDomain: 'senior-app-2adee.firebaseapp.com',
    storageBucket: 'senior-app-2adee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zvXAZUAFP_LuMR7UFlnT-Hb7Ishv9w8',
    appId: '1:874274763327:android:cfc3c0e03a3970ca25be8a',
    messagingSenderId: '874274763327',
    projectId: 'senior-app-2adee',
    storageBucket: 'senior-app-2adee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Dv_YRuhNC0NofpyztWrb7mIH3-Gx8c0',
    appId: '1:874274763327:ios:86757429430eed2025be8a',
    messagingSenderId: '874274763327',
    projectId: 'senior-app-2adee',
    storageBucket: 'senior-app-2adee.firebasestorage.app',
    iosBundleId: 'com.seniorease.seniorEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Dv_YRuhNC0NofpyztWrb7mIH3-Gx8c0',
    appId: '1:874274763327:ios:86757429430eed2025be8a',
    messagingSenderId: '874274763327',
    projectId: 'senior-app-2adee',
    storageBucket: 'senior-app-2adee.firebasestorage.app',
    iosBundleId: 'com.seniorease.seniorEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoxVimPpg8k3DkuQLvjCZwiHcmQ7aB15A',
    appId: '1:874274763327:web:54b64b2db07740e325be8a',
    messagingSenderId: '874274763327',
    projectId: 'senior-app-2adee',
    authDomain: 'senior-app-2adee.firebaseapp.com',
    storageBucket: 'senior-app-2adee.firebasestorage.app',
  );
}
